### PR TITLE
Update all k8s.io dependencies to 1.8.2 and add support for `Retain` reclaim policy to lib/controller

### PR DESCRIPTION
**Pull request by wongma7**
this is a continuation of https://github.com/kubernetes-incubator/external-storage/pull/392

snapshots needs some  code changes because of changes to kuberentes' internal API.

other than that, we are fine.

@xingzhou we can contniue work in https://github.com/kubernetes-incubator/external-storage/pull/392 if I submit a PR against your branch, or we can fix it here. up to you!

### CODE REVIEW

**Comment by wongma7** [comment]
``` bash
$ make snapshot
cd snapshot; \
make
make[1]: Entering directory '/home/mawong/src/github.com/kubernetes-incubator/external-storage/snapshot'
go build -o _output/bin/snapshot-controller cmd/snapshot-controller/snapshot-controller.go
# github.com/kubernetes-incubator/external-storage/snapshot/pkg/apis/crd/v1
pkg/apis/crd/v1/register.go:52: cannot use VolumeSnapshot literal (type *VolumeSnapshot) as type runtime.Object in argument to scheme.AddKnownTypes:
	*VolumeSnapshot does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/crd/v1/register.go:53: cannot use VolumeSnapshotList literal (type *VolumeSnapshotList) as type runtime.Object in argument to scheme.AddKnownTypes:
	*VolumeSnapshotList does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/crd/v1/register.go:54: cannot use VolumeSnapshotData literal (type *VolumeSnapshotData) as type runtime.Object in argument to scheme.AddKnownTypes:
	*VolumeSnapshotData does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/crd/v1/register.go:55: cannot use VolumeSnapshotDataList literal (type *VolumeSnapshotDataList) as type runtime.Object in argument to scheme.AddKnownTypes:
	*VolumeSnapshotDataList does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/crd/v1/types.go:292: cannot use &vd.Metadata (type *"github.com/kubernetes-incubator/external-storage/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListMeta) as type "github.com/kubernetes-incubator/external-storage/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".List in return argument
pkg/apis/crd/v1/types.go:312: cannot use &vd.Metadata (type *"github.com/kubernetes-incubator/external-storage/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListMeta) as type "github.com/kubernetes-incubator/external-storage/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".List in return argument
```

I will work on fixing this issue. everything else seems okay.

**Comment by xingzhou** [comment]
@wongma7, does this PR contain all the changes I made in #392?

**Comment by wongma7** [comment]
Yes, all I’ve done so far is change from commit hash to 1.8.1 tag and test
it pass ci. But next have to fix snapshots, which depends on the changes in
your pr

**Comment by xingzhou** [comment]
yeap, is there any reason that we need to share dependency with snapshot? to me, snapshot is some kind of independent code, which will be compiled on its own

**Comment by sbezverk** [comment]
@wongma7 it seems going with 1.8.1 tags is not enough for some newer api objects as in the latest CI failure for CephFS.

**Comment by wongma7** [comment]
* @sbezverk ty for heads up about cephfs, added TODO for https://github.com/kubernetes-incubator/external-storage/issues/309 , cephFS namespace issue @rootfs
* Added deepcopy funcs for snapshot API, CRD requires we implement them. @tsmetana PTAL

I will squash the first 3 commits @xingzhou 

Then we can get this merged finally. Sorry for the month-long delay everybody.

**Comment by wongma7** [comment]
Forgot to say, for the snapshot changes I ran
```
$ ./generate-groups.sh deepcopy github.com/kubernetes-incubator/external-storage/snapshot/pkg/apis github.com/kubernetes-incubator/external-storage/snapshot/pkg/apis "crd:v1"
```
from https://github.com/kubernetes/code-generator to get zz_generated.deepcopy.go. And manually fixed the broken ones and put into deepcopy.go. (The structs that have a member of external type i.e. from core_v1)

**Comment by sbezverk** [comment]
@wongma7 if it is possible, could you please add recent merged api change to support RBDPersistentVolumeSource which was added last week? In this case RBD provisioner can be refactored to use it.

**Comment by wongma7** [comment]
nobody wants to review, merging

**Comment by sbezverk** [comment]
@wongma7 Tested for RBD, the change looks good, now SecretReference is available. I still see the issue for new RBDPersistentVolumeSource though, I guess it will be addressed in the next PR.

pkg/provision/provision.go:114: undefined: "github.com/kubernetes-incubator/external-storage/vendor/k8s.io/api/core/v1".RBDPersistentVolumeSource
Makefile:27: recipe for target 'build' failed
